services:
  ao3_updater:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ao3_updater
    volumes:
      - type: bind
        source: /home/nekanu/Ebooks
        target: /app/books
    restart: always
    env_file: .env